-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = 1,
    [2] = {
        ["RitualsCompleted"] = {
            [1] = 0,
            [2] = 0,
            [3] = 0,
            [4] = 0,
            [5] = 0,
            [6] = 0
        },
        ["HighestLevel"] = 74,
        ["Upgrades"] = {
            ["CrateSpawnrate"] = 0,
            ["CrateCapacity"] = 0,
            ["CrateSellrate"] = 0
        },
        ["Currencies"] = {
            ["Salad"] = 0,
            ["PepperCrates"] = 0,
            ["Omelettes"] = 0,
            ["YolkCrates"] = 0,
            ["Yolks"] = 0,
            ["Peppers"] = 0,
            ["Gold"] = 19,
            ["EggCrates"] = 0,
            ["Energy"] = 0,
            ["Eggs"] = 938324823832.540527999999966
        },
        ["IgnoreSaveLimit"] = false,
        ["BoughtUpgrades"] = {
            ["60"] = "G",
            ["52"] = "G",
            ["40"] = "P",
            ["50"] = "R",
            ["54"] = "G",
            ["55"] = "G",
            ["56"] = "G",
            ["66"] = "P",
            ["206"] = "?",
            ["1"] = "E",
            ["2"] = "E",
            ["14"] = "Y",
            ["16"] = "Y",
            ["47"] = "R",
            ["31"] = "P",
            ["57"] = "G",
            ["207"] = "?",
            ["44"] = "P"
        },
        ["Match"] = "c622c0d87a20f6890fdabd60904f209a82db240ee0cf1170678ffe1bc97b995c",
        ["HighestEggs"] = 58.540527999999966,
        ["GateOpened"] = false,
        ["Experience"] = 8.959999999999999,
        ["Milestones"] = {
            ["Peppers"] = 0,
            ["Omelettes"] = 0,
            ["Yolks"] = 5,
            ["Eggs"] = 7
        },
        ["PortalActivated"] = false,
        ["Level"] = 3,
        ["Settings"] = {
            ["HideOtherPlayers"] = false,
            ["InstantReset"] = false,
            ["ScientificNotaion"] = false,
            ["GameVolume"] = 1,
            ["DisableDoubleRange"] = false,
            ["LowPerformance"] = false,
            ["MusicVolume"] = 1
        },
        ["BoiledEggs"] = 0
    }
}

game:GetService("ReplicatedStorage").RemoteFunctions.AcceptSave:InvokeServer(unpack(args))
