-- THIS REMOTE WAS PREVENTED FROM FIRING THE SERVER BY SIMPLESPY

-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = {
        ["Eggs"] = 9999999999999.67665599999998,
        ["Level"] = 5000
    }
}

game:GetService("ReplicatedStorage").RemoteEvents.SendDatastoreData:FireServer(unpack(args))
